---
route:
  group_by:
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications
receivers:
  - name: email-notifications
    email_configs:
      - to: pardeshiumesh786@gmail.com
        from: monitoring@example.com
        smarthost: smtp.gmail.com:587
        auth_username: pardeshiumesh786@gmail.com
        auth_identity: pardeshiumesh786@gmail.com
        auth_password: feku hsln ugkq icxc
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - dev
      - instance

